#
FROM dart:stable AS build

WORKDIR /app
COPY pubspec.* ./
RUN dart pub get

COPY . .
RUN dart compile exe bin/randomchatele.dart  -o bin/bin/randomchatele

FROM scratch
COPY --from=build /runtime/ /
COPY --from=build /app/bin/randomchatele /app/bin/

CMD ["/app/bin/randomchatele"]